# Generated by Django 3.1 on 2020-08-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='stype',
            new_name='type',
        ),
    ]
