# Generated by Django 3.1 on 2020-08-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200818_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='type',
            new_name='stype',
        ),
    ]
